name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
      
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release
      
      - uses: actions/upload-artifact@v4
        with:
          name: privoo-apk
          path: build/app/outputs/flutter-apk/*.apk
